### ISSUE TITLE
As a user, I want first when people look at my blog can recognize who I am

### ISSUE THREAD

**Issue by Ngdaz** [huyhandes/USTH-SE-2019#10]

**Comment by macorn** [comment]
in the first look to the blog , i want to see the user name

**Comment by huyhandes** [comment]
- [ ]  Design "Home" page
- [ ]  Design "About me" page
- [ ]  Add content and information to "About me" page
- [ ]  Design "Contact" page
- [ ]  Add content and information to "Contact" page to let people can contact me
