### ISSUE TITLE
As an user, I want when people visit my blog they can comment

### ISSUE THREAD

**Issue by Ngdaz** [huyhandes/USTH-SE-2019#8]

**Comment by Portgasdax99** [comment]
1. icon

2. linkinsertion

3. hide thread

**Comment by huyhandes** [comment]
- [x] text size
- [ ] image upload
- [ ] link insert
- [ ] icon/emoji insert
- [ ] bold/Italic/Underline
- [ ] Upvote/Downvote
- [ ] Quote
- [ ] Name or email of user
- [ ] text position
- [ ] Reply option
